### ISSUE TITLE
errors when training the deeplearning code

### ISSUE THREAD

**Issue by carrie-smy** [Unity-Technologies/Robotics-Object-Pose-Estimation#40]
INFO | 2021-11-28 19:26:19 | pose_estimation.pose_estimation_estimator | MainThread | intermediate mean orientation loss after mini batch 689 in epoch 1 is: 2.1472411858257803
INFO | 2021-11-28 19:26:19 | pose_estimation.pose_estimation_estimator | MainThread | intermediate mean translation loss after mini batch 690 in epoch 1 is: 0.049511323997453935
INFO | 2021-11-28 19:26:19 | pose_estimation.pose_estimation_estimator | MainThread | intermediate mean orientation loss after mini batch 690 in epoch 1 is: 2.1470717681108926
Traceback (most recent call last):
  File "/home/e509/miniconda3/envs/pose_estimation/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/e509/miniconda3/envs/pose_estimation/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/e509/unity/Robotics-Object-Pose-Estimation/Model/pose_estimation/cli.py", line 143, in <module>
    main()
  File "/home/e509/unity/Robotics-Object-Pose-Estimation/Model/pose_estimation/cli.py", line 133, in main
    estimator.train()
  File "/home/e509/unity/Robotics-Object-Pose-Estimation/Model/pose_estimation/pose_estimation_estimator.py", line 79, in train
    train_model(self)
  File "/home/e509/unity/Robotics-Object-Pose-Estimation/Model/pose_estimation/train.py", line 53, in train_model
    train_loop(
  File "/home/e509/unity/Robotics-Object-Pose-Estimation/Model/pose_estimation/train.py", line 85, in train_loop
    _train_one_epoch(
  File "/home/e509/unity/Robotics-Object-Pose-Estimation/Model/pose_estimation/train.py", line 128, in _train_one_epoch
    metric_translation, metric_orientation = evaluation_over_batch(
  File "/home/e509/unity/Robotics-Object-Pose-Estimation/Model/pose_estimation/evaluate.py", line 124, in evaluation_over_batch
    for index, (images, target_translation_list, target_orientation_list) in enumerate(
  File "/home/e509/miniconda3/envs/pose_estimation/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/e509/miniconda3/envs/pose_estimation/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/e509/miniconda3/envs/pose_estimation/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/e509/unity/Robotics-Object-Pose-Estimation/Model/pose_estimation/single_cube_dataset.py", line 254, in __next__
    return self.__next__()
  File "/home/e509/unity/Robotics-Object-Pose-Estimation/Model/pose_estimation/single_cube_dataset.py", line 249, in __next__
    data = json.load(file)
  File "/home/e509/miniconda3/envs/pose_estimation/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/e509/miniconda3/envs/pose_estimation/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/e509/miniconda3/envs/pose_estimation/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/e509/miniconda3/envs/pose_estimation/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by at669** [comment]
Hi, thanks for the report. So we can investigate on our end, could you provide more info by filling out the bug report template attached--particularly the steps to reproduce the error? Are you training the model on Docker or locally?

[Ticket#: AIRO-1618]

---

**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Console logs / stack traces**

Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.

**Expected behavior**

A clear and concise description of what you expected to happen.

**Screenshots**

If applicable, add screenshots or videos to help explain your problem.

**Environment (please complete the following information, where applicable):**

- Unity Version: [e.g. Unity 2020.2.0f1]
- Unity machine OS + version: [e.g. Windows 10]
- ROS machine OS + version: [e.g. Ubuntu 18.04, ROS Noetic]
- ROS–Unity communication: [e.g. Docker]
- Package branches or versions: [e.g. `com.unity.perception@0.8.0-preview.3`]

**Additional context**

Add any other context about the problem here.

**Comment by at669** [comment]
Since there has been no activity on this issue, I will close it out.
